// Code generated by protoc-gen-go-access-modifiers. DO NOT EDIT.

package example

import "github.com/kostyay/protoc-gen-go-access-modifiers/pkg/types"

func (x *PublicHelloRequest) AsPublic() {
}
func (x *PublicHelloResponse) AsPublic() {
}
func (x *PrivateHelloRequest) AsPublic() {
}
func (x *PrivateHelloResponse) AsPublic() {
}
func (x *PrivateMessage) AsPublic() {
}
func (x *PartialPrivateMessage) AsPublic() {
	var emptyField *PartialPrivateMessage
	x.Password = emptyField.GetPassword()
}
func (x *Hello) AsPublic() {
	var emptyField *Hello
	x.PrivateString = emptyField.GetPrivateString()
	x.PrivateInt = emptyField.GetPrivateInt()
	x.PrivateMessage = emptyField.GetPrivateMessage()
	if p, ok := interface{}(x.GetPrivateMessage()).(types.AsPublic); ok {
		p.AsPublic()
	}
	if p, ok := interface{}(x.GetPartialPrivateMessage()).(types.AsPublic); ok {
		p.AsPublic()
	}
}
