// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: access/v1/access.proto

package accessv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define access modifiers for methods
type MethodOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Private bool `protobuf:"varint,1,opt,name=private,proto3" json:"private,omitempty"`
}

func (x *MethodOption) Reset() {
	*x = MethodOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_access_v1_access_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOption) ProtoMessage() {}

func (x *MethodOption) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOption.ProtoReflect.Descriptor instead.
func (*MethodOption) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{0}
}

func (x *MethodOption) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

// Define access modifiers for fields
// FieldOption access modifiers for fields
type FieldOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Private bool `protobuf:"varint,1,opt,name=private,proto3" json:"private,omitempty"`
}

func (x *FieldOption) Reset() {
	*x = FieldOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_access_v1_access_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOption) ProtoMessage() {}

func (x *FieldOption) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOption.ProtoReflect.Descriptor instead.
func (*FieldOption) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{1}
}

func (x *FieldOption) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

var file_access_v1_access_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOption)(nil),
		Field:         7338840,
		Name:          "access.v1.mo",
		Tag:           "bytes,7338840,opt,name=mo",
		Filename:      "access/v1/access.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOption)(nil),
		Field:         7338839,
		Name:          "access.v1.fo",
		Tag:           "bytes,7338839,opt,name=fo",
		Filename:      "access/v1/access.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// See `FieldOption`.
	//
	// optional access.v1.MethodOption mo = 7338840;
	E_Mo = &file_access_v1_access_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// See `FieldOption`.
	//
	// optional access.v1.FieldOption fo = 7338839;
	E_Fo = &file_access_v1_access_proto_extTypes[1]
)

var File_access_v1_access_proto protoreflect.FileDescriptor

var file_access_v1_access_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x2e, 0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22,
	0x27, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x4a, 0x0a, 0x02, 0x6d, 0x6f, 0x12, 0x1e,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd8,
	0xf6, 0xbf, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x02, 0x6d, 0x6f, 0x3a, 0x48, 0x0a, 0x02, 0x66, 0x6f, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd7, 0xf6, 0xbf, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x66, 0x6f, 0x42, 0x4a,
	0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x73,
	0x74, 0x79, 0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d,
	0x67, 0x6f, 0x2d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2d, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2f, 0x76,
	0x31, 0x3b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_access_v1_access_proto_rawDescOnce sync.Once
	file_access_v1_access_proto_rawDescData = file_access_v1_access_proto_rawDesc
)

func file_access_v1_access_proto_rawDescGZIP() []byte {
	file_access_v1_access_proto_rawDescOnce.Do(func() {
		file_access_v1_access_proto_rawDescData = protoimpl.X.CompressGZIP(file_access_v1_access_proto_rawDescData)
	})
	return file_access_v1_access_proto_rawDescData
}

var file_access_v1_access_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_access_v1_access_proto_goTypes = []interface{}{
	(*MethodOption)(nil),               // 0: access.v1.MethodOption
	(*FieldOption)(nil),                // 1: access.v1.FieldOption
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),  // 3: google.protobuf.FieldOptions
}
var file_access_v1_access_proto_depIdxs = []int32{
	2, // 0: access.v1.mo:extendee -> google.protobuf.MethodOptions
	3, // 1: access.v1.fo:extendee -> google.protobuf.FieldOptions
	0, // 2: access.v1.mo:type_name -> access.v1.MethodOption
	1, // 3: access.v1.fo:type_name -> access.v1.FieldOption
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_access_v1_access_proto_init() }
func file_access_v1_access_proto_init() {
	if File_access_v1_access_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_access_v1_access_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_access_v1_access_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_access_v1_access_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_access_v1_access_proto_goTypes,
		DependencyIndexes: file_access_v1_access_proto_depIdxs,
		MessageInfos:      file_access_v1_access_proto_msgTypes,
		ExtensionInfos:    file_access_v1_access_proto_extTypes,
	}.Build()
	File_access_v1_access_proto = out.File
	file_access_v1_access_proto_rawDesc = nil
	file_access_v1_access_proto_goTypes = nil
	file_access_v1_access_proto_depIdxs = nil
}
