on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.17'
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

  buf:
    name: buf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.17'
          cache: false
      - uses: actions/checkout@v3
      - name: buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: '0.57.0'
      - name: buf lint
        run: |
          buf lint
      - name: buf breaking
        run: |
          buf breaking --against-input '.git#branch=main'